
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = 'a5887f9-dirty'
version_full = 'a5887f96484cf76dbe8cfefb13badf2f356e02be-dirty'
version_branch = 'master'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full, 'branch': version_branch}

